name: run_unit_test

on:
  push:
    branches:
    - main

jobs:
  reun_unit_tests:
      runs-on: ubuntu-latest

      steps:
          - name: Checkout Repository
            uses: actions/checkout@v2.5.0
            with:
             fetch-depth: 0

          - name: unit_tests
            run: gcc -o unit_test test.c sum.c -lcriterion && ./unit_test